- Chart.yaml
- templates/daemonset.yaml
- templates/statefulset.yaml
Fixes #12 
Made the master machine GUID persistent as well, in case anyone wants to stream master data to another netdata somewhere.
> Use persistent GUIDs per hostname

- Chart.yaml
- templates/statefulset.yaml
Fixes #14 
Added serviceName to statefulset.yaml spec.
> Add serviceName to statefulset spec

- Chart.yaml
- README.md
- templates/configmap.yaml
- templates/daemonset.yaml
- templates/statefulset.yaml
- values.yaml
Hi,
I don't like to modify the source code of the helm package, if I need to enable some plugin. So I add such possibility.
Thanks
> add ability to manage custom configs

- Chart.yaml
- README.md
- values.yaml
Use netdata v1.15.0 tag
Add @kam1kaze to maintainers
Modify README to reflect the change in the way config files are defined.
> Use v1.15.0, update readme, update maintainers

- Chart.yaml
- values.yaml
Hadn't updated values.yaml in version changes.
> Correct version update

- Chart.yaml
- README.md
- Increase chart version due to PRs #57 and #58 
- Increase minimum required k8s version to 1.9, due to #57 
- Correct README.md for the default value of the image (it just had a static version).
> Update chart version and minor README fixes

- Chart.yaml
- templates/daemonset.yaml
- templates/statefulset.yaml
fixes https://github.com/netdata/helmchart/issues/45#issuecomment-550554831
Stop trying to create reproducible UUIDs, it will not happen.
Details of what was happening and the RCA are in https://github.com/netdata/helmchart/issues/45
> Fix slave pods not starting due to `netdata.public.unique.id`

- values.yaml
Fixes: #66
Related: https://github.com/netdata/netdata/issues/7188
> coredns, kubelet: add additional job

- README.md
- templates/service.yaml
- values.yaml
I need to be able to set a static loadbalancer IP so it is reproducable. Probably others as well ;-)
> Support for static loadbalancerIP

- README.md
- values.yaml
> Documents how to disable anonymous statistics via DO_NOT_TRACK

- templates/daemonset.yaml
fixes #92
use alpine-based image with installed `wget` instead of busybox
> daemonset nodeuid init container: busybox wget => gnu wget

- README.md
As @ilyam8 requested over at netdata/agent-service-discovery#24, this is perhaps the better place to list which services can be discovered with the sd sidecar.
**Only to be merged after #102 is merged.**
> Update README with supported services

- README.md
> fix link to `chaoskube` helm chart in the readme

- Chart.yaml
- templates/persistentvolumeclaim.yaml
The condition for the database storageClass is wrong (copy paste error?).
> Fix storageClass condition

- templates/deployment.yaml
- values.yaml
One of the advantages is that we need to update the version number in one place only.
> Make image.tag in values.yaml follow Chart.AppVersion

- Chart.yaml
- templates/daemonset.yaml
To complete the change from #147
> Render child DaemonSet container image with `tpl`

- tools/update_helmchart.sh
{{ .Chart.AppVersion }} is used instead. Ref: #147
> tools/update_helmchart.sh: values.yaml no longer contains a static app version

- README.md
- templates/daemonset.yaml
- templates/deployment.yaml
- values.yaml
> Make liveness and readiness probe parameters configurable from values.yaml

- index.html
> Add a official helm chart repo landing page

- charts/netdata/Chart.yaml
- charts/netdata/README.md
- tools/update_helmchart.sh
- Add version badges
- Remove URL from Chart.yaml/description
- Update README.md's path in tools/update_helmchart.sh
- Bump version
> Add version badges

- .github/CODEOWNERS
@knatsakis i guess we need to remove @cakrit too.
whom to add? @Ferroin and probably me?
> remove ncmans prologic from CODEOWNERS

- charts/netdata/Chart.yaml
- charts/netdata/README.md
> Update to Agent version 1.29.0 and chart version 3.4.3.

- charts/netdata/Chart.yaml
- charts/netdata/README.md
> Update to Agent version 1.29.1 and chart version 3.5.1.

- charts/netdata/Chart.yaml
- charts/netdata/README.md
> Update to Agent version 1.29.2

- charts/netdata/Chart.yaml
- charts/netdata/README.md
> Update to agent version 1.29.3.

- .github/dependabot.yml
> Add dependabot config to update Github Actions.

- charts/netdata/Chart.yaml
- charts/netdata/README.md
- charts/netdata/values.yaml
ref #229
fixing the bug for issue mentioned https://community.netdata.cloud/t/metrics-missing-for-nodes-in-cloud/1697/5
> changing default memory modes

- charts/netdata/templates/psp.yaml
ref #148 
restrictions to the PSP:
- decrease in capabilities,
- privileged setting removed.
> restrictions to psp

- .github/workflows/release.yml
https://github.com/ilyam8/helmchart/runs/5018544354?check_suite_focus=true
> ci: do not run release GHA job on forks

- charts/netdata/sdconfig/child.yml
Related to netdata/netdata#12572
> add 'app' config option to SD's prometheus jobs

- charts/netdata/templates/clusterrole.yaml
Needed for netdata/go.d.plugin#673
> add nodes resource to clusterrole

- .github/workflows/release.yml
Should be merge after our on infra repository  PR's (2187)
The secret added. In order not to commit Private repository names
> feat: Update release workflow

- charts/netdata/templates/daemonset.yaml
- charts/netdata/templates/deployment.yaml
- charts/netdata/values.yaml
Replacing if/else branch in templates with the ternary function in values.
> chore: simplify streaming on/off logic

- charts/netdata/values.yaml
Changed in netdata/netdata https://github.com/netdata/netdata/pull/13856
> change claiming url to api.netdata.cloud

- charts/netdata/templates/daemonset.yaml
Fixes netdata/netdata#14394
inb4 git blame
> fix child config

- charts/netdata/values.yaml
it is no longer global.memory_mode, but db.mode.
> update db mode config

- charts/netdata/README.md
Learn gets confused and generates a broken link
> Remove link to values.yaml

- charts/netdata/README.md
- charts/netdata/templates/daemonset.yaml
- charts/netdata/values.yaml
Implements netdata/netdata#14843
See for details netdata/netdata#14891.
Tested the changes in my kind cluster.
> add option to query Kubelet for Pod metadata

- charts/netdata/sdconfig/child.yml
Not a problem for the current version of Netdata, 4k is too small.
> increase sd prometheus max_time_series

- charts/netdata/README.md
> update helm min required version to 3.8

- charts/netdata/templates/child/daemonset.yaml
- charts/netdata/templates/k8s-state/deployment.yaml
- charts/netdata/templates/parent/deployment.yaml
- charts/netdata/values.yaml
This will work with all memory modes.
Closes: #434
> use 'netdatacli ping' for liveness/readiness probes

- charts/netdata/templates/child/daemonset.yaml
- charts/netdata/templates/k8s-state/deployment.yaml
- charts/netdata/templates/parent/deployment.yaml
trigger restart also on changes in secret maps
> fix: restart on secret map changes

- charts/netdata/values.yaml
> bump agent sd v0.2.10

- charts/netdata/values.yaml
Expected to be `/host/root` (netdata/netdata#18035)
> update extra volume hostroot example

- .github/workflows/checks.yml
> bump chart-testing-action v2.7.0

- charts/netdata/templates/clusterrole.yaml
Needed for netdata/netdata#19657
> add deployments to clusterrole
