netdata/helmchart

templates/clusterrole.yaml

I think this will not work in Kubernetes. `apiGroups: ["quota.openshift.io"]` is API group only in OpenShift

Changed rbac

---

templates/daemonset.yaml
templates/statefulset.yaml
values.yaml

I have added the ability to add environment variables into values.yaml. Now you can add new environment variables in values.yaml or set up them with --set flag, also I have added couple meta information in environment variables about a pod name and namespace.
Example: 
`helm install --name netdata ./ --dry-run --debug --set master.env.LOG_LEVEL=debug,master.env.PORT=80`
```
...
env:
- name: MY_POD_NAME
valueFrom:
fieldRef:
fieldPath: metadata.name
- name: MY_POD_NAMESPACE
valueFrom:
fieldRef:
fieldPath: metadata.namespace
- name: LOG_LEVEL
value: "debug"
- name: PORT
value: "80"
...
```
*p.s. variables LOG_LEVEL and PORT are fictional*

Added dynamic and metadata environment

---

Chart.yaml
README.md
templates/configmap.yaml
templates/statefulset.yaml
values.yaml

Related to #1 
- Moved standard config contents to values.yaml
- Added sample example alarm configuration for the master
- Updated README, also with instructions on how to add more config files.

Extend configuration file support and update README

---

templates/daemonset.yaml
templates/statefulset.yaml

References:
https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/
https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods
https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/

Add preStop to ensure graceful shut down gracefully before the pod is removed

---

Chart.yaml
values.yaml

Leave only the bare minimum collectors on the master, it's the slaves that do the work.

Disable plugins from the master

---

Chart.yaml
README.md
templates/daemonset.yaml
templates/statefulset.yaml
values.yaml

Hi,
I need to set `vm.max_map_count` sysctl param to bypass the `Cannot allocate memory` issue. So I added the init container, where sysctl params could be managed.
Thanks

add sysctl init container

---

Chart.yaml
templates/daemonset.yaml
values.yaml

- Use netdata v1.14.0
- Add liveness/readiness probe on slaves (enable web server to do it)
- Make slaves run in memory mode none
Fixes #16.

Slave liveness probe and memory mode none, use netdata v1.14

---

README.md

The label should be `master.alarms.volumesize` instead of duplicated `master.database.volumesize` as in https://github.com/netdata/helmchart/blob/b9251cd40947b7b1a1024aa8fd2ef79ec3aac0dc/templates/statefulset.yaml#L30

Fix wrong parameter name in readme

---

README.md

Just caught up another typo in the readme while tinkering with the chart.
Edited to correspond with:
https://github.com/netdata/helmchart/blob/c72a62e2f6095e4f222d026f7272d8cda26d1967/templates/configmap.yaml#L12

Correct another wrong parameter name in readme

---

Chart.yaml
README.md
templates/configmap.yaml
templates/daemonset.yaml
values.yaml

Fixes #21 
The stock configs already enabled k8s monitoring for kubelet, kubeproxy and coredns, but added the option of overriding the settings in values.yaml. 
Other minor changes in this PR:
- Add a newline at the end of each config file (actually with some spaces on the last line too, but I couldn't find a way to avoid it).
- Fix the tag in values.yaml to v1.14.0

k8s monitoring configuration

---

Chart.yaml
templates/daemonset.yaml
templates/statefulset.yaml
values.yaml

Fixes #17 and #25 
Summary of the features and fixes
1. Support toggling of persistence volumes for database and alarms
2. Fix `master.alarms.storageclass` being used for claiming volume for database too
3. Add apiVersion in Chart.yaml as it's required in helm3 and canary version of helm2 also shows linting error for the same
4. Fix `maintainers` key in Chart.yaml
5. Fix env field being in pod spec instead of inside container spec, in both DaemonSet and StatefulSet
cc @cakrit @varyumin . Please review 😄

Persistence toggle and fixes

---

Chart.yaml
README.md
templates/daemonset.yaml
templates/statefulset.yaml
values.yaml

This will allow the master and slave pods to be labeled and annotated
with user-defined values, in addition to the default labels and
annotations included in the chart.
closes #33

Allow custom labels and annotations to be set on pods.

---

README.md

Related to #36 
`master.database.persistence` and `master.alarms.persistence` were missing from the table of options.

Add documentation of the persistent volume flags

---

Chart.yaml
values.yaml

Use 1.16.0
Disable remaining plugins, as the master isn't meant to be monitoring anything, just maintains the DB.

Upgrade version and remove all charts from the master

---

Chart.yaml
templates/daemonset.yaml

Based on examples here: https://kubernetes.io/docs/tutorials/clusters/apparmor/ I think this annotation needs to be on the pods themselves to get through PSP checks.

Move apparmor annotation to pod template

---

Chart.yaml
README.md
templates/daemonset.yaml
values.yaml

In https://github.com/netdata/helmchart/commit/c0fa186ddcbd9be488309dbffb85d9f57b521ab8 I missed that there was an existing annotations block.
This also makes the AppArmor annotation configurable (though on by default).
Fixes https://github.com/netdata/helmchart/issues/40
Signed-off-by: Charlie Egan <charlieegan3@users.noreply.github.com>

Correctly set DaemonSet AppArmor annotation

---

templates/statefulset.yaml

In kubernetes v1.16 the deprecated `apps/v1beta2` for StatefulSet is removed [1].
Deployment is failing with:
```
microk8s.helm install --name my-release ./netdata
Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"
```
[1] https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

Statefulset api version is now apps/v1

---

README.md
templates/statefulset.yaml
values.yaml

I think using the default storage class is a more sane default value for the `storageclass`.
Also, since the empty string as storage class has a special meaning we use "-" to denote the absence of storageclass (resulting to selecting the default storageclass) [1]
[1] https://github.com/helm/helm/issues/2600

Use by default the default storage class for PVCs

---

README.md
templates/configmap.yaml
templates/daemonset.yaml
values.yaml

**Reasoning:**   
I'd like to install only master with this helmchart via helmfile together with rest of the components which are installed with helmfile. Currently I have to template chart with helm and remove slave configmap and daemonset files. I run netdata (close to our prometheus instance which is then scraping the netdata) in managed K8s cluster where I don't have possibility to access worker nodes data as those have their own managed monitoring solution so there's no reason to deploy the slave daemonset. I'd like to use it as streaming master for netdata instances running in openstack VMs.

Optionally disable daemonset

---

README.md
templates/daemonset.yaml
values.yaml

Fixes: #61
This PR adds persistence of netdata slaves `netdata.public.unique.id` value. 
When this PR is merged netdata slaves will use local node `metadata.uid` as `netdata.public.unique.id`.
___
I tested this feauture on GKE.
All slaves/nodes:
```cmd
$ kubectl get pods --selector=app=netdata --selector=role=slave -o wide
NAME                  READY   STATUS    RESTARTS   AGE   IP            NODE                                                NOMINATED NODE   READINESS GATES
netdata-slave-ltmfg   1/1     Running   0          31m   10.128.0.32   gke-standard-cluster-2-default-pool-86353fdd-b7zb   <none>           <none>
netdata-slave-rcrkj   1/1     Running   0          31m   10.128.0.31   gke-standard-cluster-2-default-pool-86353fdd-494b   <none>           <none>
netdata-slave-tqhdt …
```

add slave netdata.public.unique.id persistence

---

templates/daemonset.yaml

This PR adds `MY_NODE_NAME` env var to the netdata-slave daemonset. It allows us to use `fieldSelect` query parameter doing `api/v1/pods` call. We dont need to query pods for the whole cluster, we need to query all pods for the specific node.
Docs:
> https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#list-all-namespaces-pod-v1-core
Cgroup-name.sh script:
https://github.com/netdata/netdata/blob/fce6650a689625f3a591cf79046395b62c9687f9/collectors/cgroups.plugin/cgroup-name.sh.in#L89-L110
___
available since 1.4 (https://github.com/kubernetes/kubernetes/pull/27880)

netdata-slave: add MY_NODE_NAME env var

---

Chart.yaml
README.md
templates/daemonset.yaml
templates/statefulset.yaml
values.yaml

This is useful for infrastructure components and especially monitoring that needs to be there when things go wrong. Without a custom priority class, netdata agents can be killed under resource pressure just when you need them to be recording stats.
[Some](https://github.com/helm/charts/blob/6c7638eef1730a6e4de48f37fa3262a427106885/stable/prometheus/values.yaml#L48) other [charts](https://github.com/helm/charts/blob/6c7638eef1730a6e4de48f37fa3262a427106885/stable/datadog/values.yaml#L454) with this config.

Add priority class name

---

.gitignore
Chart.yaml
README.md
tools/update_helmchart.sh
values.yaml

Also adds a tool to do this some-what automatically until we trust that the
tool does the right thing 100% of the time; then we'll integrate this into a
GHA workflow.
See `./tools/tools/update_helmchart.sh`. Usage is simple:
```#!sh
$ ./tools/tools/update_helmchart.sh
```
Which will bump the `patch` version by default.
Otherwise:
```#!sh
$ ./tools/tools/update_helmchart.sh v1.22.0
```
To update to a new version entirely.
The functions herein are 100% POSIX Sh compliant and the version parsing and
handling supports `x.y.z` as well as optional build `x.y.z-b` and bumping
any component with resetting others to zero as appropriate (_untested_).

Bump NetData Helm Chart from v1.21.0 => v1.21.1

---

templates/configmap.yaml

ssia
it allows to use `--set-file` option
Tests:
- value not set
- value type is `string`
- value type is `map`

sd child configmap template: handle "string" value

---

Chart.yaml
README.md
templates/daemonset.yaml
values.yaml

Fixes: #113
Tests:
- default, `updateStrategy` not set
```cmd
0 helmchart (ds_updateStrategy)$ helm template -s templates/daemonset.yaml . | yq -P r - spec.updateStrategy
0 helmchart (ds_updateStrategy)$
```
- `updateStrategy` set
```cmd
0 helmchart (ds_updateStrategy)$ helm template -s templates/daemonset.yaml --set child.updateStrategy.type=RollingUpdate,child.updateStrategy.rollingUpdate.maxUnavailable=1 . | yq -P r - spec.updateStrategy
rollingUpdate:
maxUnavailable: 1
type: RollingUpdate
```

child: add `updateStrategy` option

---

README.md

As stated in the title, this PR adds links to the new k8s documentation and guide that were both recently published. I also cleaned up the README a bit, and aligned some of the commands with those in the k8s install doc.

Add links to k8s documentation + guide and cleanup

---

Chart.yaml
README.md
templates/statefulset.yaml
values.yaml

Fixes: https://github.com/netdata/helmchart/issues/79
**This PR**
* add parent agent claiming command for netdata cloud
**Related:**
* PR https://github.com/netdata/helmchart/pull/111
* Issue https://github.com/netdata/helmchart/issues/79
**Tests:**
**Test Environment:**
Kubernetes cluster v1.16.10 in AWS boostraped with Kops 1.16.3
Signed-off-by: Luis Garnica <lgarnica@geoblink.com>

add parent agent claiming command for netdata cloud

---

README.md
templates/deployment.yaml
templates/persistentvolumeclaim.yaml
values.yaml

Fixes #86 
Tested locally on a kind cluster:
- PVC are created and mounted correctly
- Changing parent's deployment results in first the existing parent pod terminating and then a new one being created.

Convert parent statefulset to deployment

---

README.md

As requested by @cakrit in netdata/netdata#9774. This information also exists in the k8s install docs, but it makes sense to have it here as well.
I don't have access to a k8s cluster any more, so if anyone has ideas how to make this process smoother, perhaps by using `kubectl edit` on a running cluster, I'm happy to hear it.

Add service discovery configuration details

---

sdconfig/child.yml
values.yaml

blocked by:
Blockers are resloved.
---
Fixes: netdata/netdata#9774
This PR changes service discovery config, it adds identification prometheus enpoints via well-known annotations:
- `prometheus.io/scrape`: The default configuration will scrape all pods and, if set to false, this annotation will exclude the pod from the scraping process.
- `prometheus.io/path`: If the metrics path is not /metrics, define it with this annotation.
- `prometheus.io/port`: Scrape the pod on the indicated port instead of the pod’s declared ports (default is a port-free target if none are declared).
I tested this PR locally in minikube and on gke.

sdconfig: add prometheus endpoints identification using `prometheus.io/scrape` annotation

---

README.md
templates/daemonset.yaml
templates/deployment.yaml
values.yaml

The default shutdown time (30 seconds) is not enough for parent node in our case. Time-to-time we get a corrupted database during node maintenance/lifecycle (we are using preemptible nodes on dev environment). So we would like to control shutdown time.
BTW, lifecycle.preStop does not help in this case. Bcz if the preStop hook hangs during execution, the Pod phase stays in a Terminating state and is killed after terminationGracePeriodSeconds of pod ends [(doc)](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution).
I would like to suggest to increase the default value of `parent.terminationGracePeriodSeconds` up to 300 seconds by default. Such value will be more friendly for users with slow IO or big databases.

Add ability to control graceful shutdown period

---

charts/netdata/templates/daemonset.yaml
charts/netdata/templates/deployment.yaml
charts/netdata/values.yaml

This requires v1.26 or newer of the agent's docker image in order to work.

Fix changing netdata's listen port

---

charts/netdata/Chart.yaml

To be merged after Helm v2 EOL (Nov 13th 2020)
https://helm.sh/blog/helm-v2-deprecation-timeline/

charts/netdata/Chart.yaml: Upgrade to Helm v3

---

charts/netdata/Chart.yaml
charts/netdata/README.md
charts/netdata/templates/daemonset.yaml

There is webhook on GKE - it sets `resources->requests->cpu: 100m` if the parameter is empty.
I think it is ok to have minimal and hardcoded cpu req for `init-nodeuid` init container.
---
Every time i install nd via helmchart on my potato cluster i have to tune this parameter b/c one node has no 100m of cpu 😄

nd child init nodeuid container: set minimal cpu requests

---

charts/netdata/README.md

Related to netdata/netdata#10172, where I'm updating the official k8s install/configure procedures to use the Helm repo rather than cloning this repoy.
I noticed a few areas where the new chart path wasn't updated from `./netdata-helmchart` to `./netdata-helmchart/charts/netdata`, so I aligned those, and did a little bit more housekeeping.

Clean up README and align chart path

---

charts/netdata/Chart.yaml
charts/netdata/README.md
charts/netdata/templates/clusterrole.yaml

This is needed to get `kube-system` namespace uid, plan to use it as cluster_id.

allow netdata to get/list namespaces

---

CODE_OF_CONDUCT.md
charts/netdata/README.md

I am in the middle of an effort to align our repositories for the contributors. 
This PR adds a small contributing section and removes the CoC (we use default GitHub health files, check netdata/.github repo)

Align repo

---

.github/workflows/agent-pr.yml

This restructures the GHA workflow responsible for generating agent version update PRs so that it produces verified commits by using the GitHub API to generate the commit instead of generating it locally on the runner and then pushing to GitHub. Making sure these commits are verified is important to helping foster user trust.
The resultant workflow is technically more verbose, but actually has one less step than the original approach did.

Restructure agent PR generation to produce verified commits.

---

charts/netdata/Chart.yaml
charts/netdata/templates/ingress.yaml

I'm really sorry that my #205 was not completed and I forgot to patch the Ingress object.
This PR should fix compatibility with K8S >= 1.19 and replaces #210
This is correct that K8S 1.19 still supports networking.k8s.io/v1beta1 but then very soon kubectl will report deprecations and it is better idea to detect used version and change slightly the resource based on desired version.
In Google Cloud now 1.19 is a main version since this week and then more and more people will need this bug fixed.

Fix Ingress for K8s >= 1.19

---

charts/netdata/Chart.yaml
charts/netdata/README.md
charts/netdata/templates/daemonset.yaml
charts/netdata/templates/deployment.yaml

This PR changes claiming logic from using [command line](https://learn.netdata.cloud/docs/agent/claim#netdata-agent-command-line) to [environment variables](https://learn.netdata.cloud/docs/agent/claim#using-environment-variables).
The latter is better because we [don't try to claim on every container start if it is already claimed](https://github.com/netdata/netdata/blob/e4f0ae2290a36bb1b9184fffac1e9ed1f707c52e/packaging/docker/run.sh#L23-L28).
---
⚠️ Claiming using environment variables works since v1.30.0 ([there was a bug in prev versions](https://github.com/netdata/netdata/pull/10811)). Do we need to keep support for old versions? (fallback to _command line_ claiming if version < 1.30.0 ).
@Ferroin @knatsakis ?
**This PR doesn't keep compatibility: Netdata version < 1.30.0 + claiming …

use environment variables for claiming

---

.github/workflows/checks.yml

**Issue:** #81 
**Scope:**  Adding new workflow to check Helm charts in Pull Requests.
**Description:**
- Version bumping done via `Agent Version PR` Workflow, Which i could not test. I think we could enable version increment  checks here once you approve this. For now i kept it disable.
-  Helm insists that Chart Maintainers Names will be the VCS usernames,  I've tested it  the tests will pass if i will rename all maintainers names, as described [here](https://github.com/helm/chart-testing/issues/192). Can be enabled as well.

Adding checks Workflow

---

.github/workflows/release.yml

Using the Netdata bOT token to be able to push back on protected branch, I've tested it in my forked repo including the correct branch settings 
`NETDATABOT_GITHUB_TOKEN` secret already in place

using NetdataBot token for release workflow

---

charts/netdata/Chart.yaml
charts/netdata/README.md

Since this [Action](https://github.com/netdata/helmchart/actions/runs/1438920238) failed before committing back the files into `master` currently we release `3.7.2` and didn't bump it.
This PR should align the version documented to the one released
Expecting No version bump once merged
Sorry for the aftermath

[skip ci] increasing version to align with the release

---

charts/netdata/templates/clusterrole.yaml

Related to #148
ssia, I don't know why we have so many resources in our ClusterRole. I guess it was copy/paste from some other helmchart 🤷‍♂️ 
I tested these changes in my GKE cluster, no problems were observed:
- cgroups name resolution works ([cgroup-name.sh](https://github.com/netdata/netdata/blob/9676eff1bc6dfc28e8f1c4857786ec05613b2646/collectors/cgroups.plugin/cgroup-name.sh.in#L216-L246))
- pod labels are in host_labels ([get-kubernetes-labels.sh](https://github.com/netdata/netdata/blob/master/daemon/get-kubernetes-labels.sh.in))
- no errors in service discovery container logs

remove unused resources from ClusterRole

---

charts/netdata/sdconfig/child.yml

Was investigating why we have no some of our cloud services monitored and found the cause - the amount of returned time series > the limit.

increase prometheus collector max_time_series limit to 4k

---

.github/workflows/agent-pr.yml

GitHub release a security patch that broke this action we are using to  create PR. [Ref](https://github.com/repo-sync/pull-request/issues/84)
A fix has been introduced in the mentioned action

fix: bump version of repo-sync to v2.6.2

---

charts/netdata/templates/clusterrole.yaml

Required for go.d/k8s_kubelet when kubelet's insecure endpoint is disabled

Add nodes/metrics ressource in clusterRole

---

charts/netdata/values.yaml

- we [enabled by default](https://github.com/netdata/netdata/pull/13158)
- we want to enable ML only on parent instances

disable ML on children instances

---

charts/netdata/values.yaml

This PR bumps the sd image to [v0.2.4](https://github.com/netdata/agent-service-discovery/releases/tag/v0.2.4) which fixes [vulnerabilities in netdata/agent-sd:v0.2.3](https://artifacthub.io/packages/helm/netdata/netdata?modal=security-report).
Fixes: #257

bump sd image tag to v0.2.4

---

charts/netdata/templates/deployment.yaml

reason for that is pretty simple. Upgrade is stuck with:

Update to deployment strategy for k8s state

---

charts/netdata/values.yaml

This PR bumps the sd image to [v0.2.6](https://github.com/netdata/agent-service-discovery/releases/tag/v0.2.6).

chore: bump sd image version to v0.2.6

---

charts/netdata/values.yaml

ssia, bump to [v0.2.8](https://github.com/netdata/agent-service-discovery/releases/tag/v0.2.8)

bump agent-sd to v0.2.8

---

charts/netdata/README.md
charts/netdata/templates/_helpers.tpl
charts/netdata/templates/cronjob.yaml
charts/netdata/templates/role.yml
charts/netdata/templates/rolebinding.yaml
charts/netdata/templates/serviceaccount.yaml
charts/netdata/values.yaml

This PR adds netdata restarter cronjob. Implements the 2nd item from #337.
Tested on local k8s cluster.

feat: add netdata-restarter cronjob

---

charts/netdata/templates/clusterrole.yaml

This is needed to gather Pods metadata from Kubelet. See netdata/netdata#14843.

add nodes/proxy to clusterrole

---

charts/netdata/README.md

If you take a look at https://learn.netdata.cloud/docs/installation/install-on-specific-environments/kubernetes/kubernetes-helm-chart-reference you will see that the badges don't work, and I found that the only way to have them render properly in both places is to have them in the arrangement proposed.
Also, ahrefs reported that some 3XX pages were receiving organic traffic, that led me to find out that there were a lot of Learn links in this file.

Documentation, Fix organic traffic on 3XX pages, and make badges render properly both on GitHub and Learn 

---

charts/netdata/sdconfig/child.yml

Tested in our sandbox cluster. This change is needed to create data collection jobs for consul-dataplane (envoy) sidecars.

add consul envoy to sdconfig

---

charts/netdata/README.md

Ingest was crashing due to https://github.com/netdata/go.d.plugin/pull/1166 not removing the links inside our docs

Remove lighttpd2 from helmchart README

---

.github/workflows/checks.yml
.github/workflows/release.yml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
TL;DR
> name: Save state
> run: echo "::save-state name={name}::{value}"
> 
> name: Set output
> run: echo "::set-output name={name}::{value}"
> 
> name: Save state
> run: echo "{name}={value}" >> $GITHUB_STATE
> 
> name: Set output
> run: echo "{name}={value}" >> $GITHUB_OUTPUT
Ref: https://github.com/netdata/infra/issues/3541

Replace deprecated set-output with ...>> $GITHUB_OUTPUT

---

charts/netdata/sdconfig/child.yml

Reverts netdata/helmchart#357
This can result is really a lot of metrics => and much bigger memory requirements. Should be a configuration option (in values), not default.

Revert "increase sd prometheus max_time_series"

---

charts/netdata/README.md
charts/netdata/templates/_helpers.tpl
charts/netdata/templates/configmap.yaml
charts/netdata/templates/daemonset.yaml
charts/netdata/templates/deployment.yaml
charts/netdata/templates/secrets.yaml

To lift the security level it is good to store sensitive data inside the Kubernetes secret instead of configmaps. Each of the configurations can be customized by setting the `storedType:  secret`, by default it will be stored as a configmap when no specified. 
This change can help us to not expose any sensitive data like database credentials to users with the built-in `view` cluster roles which don't provide access to the Kubernetes secrets.

feat: add option to store configuration as secrets

---

charts/netdata/templates/daemonset.yaml
charts/netdata/values.yaml

Hi!
In Kubernetes 1.24, dockershim and /var/run/docker.sock are deprecated in favor of CRI.
We have looked that netdata uses /var/run/docker.sock  to collect containers metadata, logs, and metrics  and is not possible to read it from helm values.
Please, give me your thoughts about it.
Thank you in advance.
Links related:
https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/
https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents/
https://aws.amazon.com/es/blogs/containers/all-you-need-to-know-about-moving-to-containerd-on-amazon-eks/

Remove /var/run/docker.sock mount

---

charts/netdata/values.yaml

Update service discovery to [v0.2.9](https://github.com/netdata/agent-service-discovery/releases/tag/v0.2.9).

bump sd image to v0.2.9

---

charts/netdata/Chart.yaml
charts/netdata/README.md

Chart versioning workflow fails due to [this](https://github.com/netdata/helmchart/actions/runs/6119022233 ) workflow (initially executed 4 days ago) previously failing to bump the version in Chart.yaml, but having pushed the release tag for 3.7.70 
We seem to have a logical error in this workflow. Release tag shouldn't be pushed if workflow fails for whatever reason and version isn't updated in Chart.yaml.
Will add a task to fix this.

New Chart version to 3.7.70

---

.github/workflows/release.yml

Tag release step happens before committing the new version of the helmchart in Chart.yaml. This can lead to inconsistencies and cause following release actions to fail since "next" release tag has been pushed to remote but current_version on Chart.yaml is still the previous, so it always try to push an existing version.
This commit adds a check if commit step failed and deletes the previously pushed release tag
This way we can avoid cases where we have to manually edit Chart.yaml version as happened: https://github.com/netdata/helmchart/pull/386
ref: https://github.com/netdata/infra/issues/3820

Delete uncommitted release tag

---

charts/netdata/values.yaml

IMO setting the taint effect `NoSchedule` for the k8sState component is not required. Moreover during node upgrade, when you mark a selected node as unschedulable the pod with k8sState still can be scheduled on that node because of the taint and it slows down the upgrade process.

empty tolerations for the k8sstate

---

charts/netdata/templates/configmap.yaml
charts/netdata/templates/cronjob.yaml
charts/netdata/templates/daemonset.yaml
charts/netdata/templates/deployment.yaml
charts/netdata/templates/ingress.yaml
charts/netdata/templates/persistentvolumeclaim.yaml
charts/netdata/templates/role.yml
charts/netdata/templates/rolebinding.yaml
charts/netdata/templates/secrets.yaml
charts/netdata/templates/service.yaml
charts/netdata/templates/serviceaccount.yaml

Using the helm built-in `.Release.Namespace` as per: https://helm.sh/docs/chart_template_guide/builtin_objects/

add namespace property to all namespaced objects

---

charts/netdata/templates/daemonset.yaml

Needed by systemd-journal plugin.

child: mount /var/log

---

charts/netdata/README.md

@ilyam8 this can be merged last and then you run ingest to get the change
dependent on https://github.com/netdata/netdata/pull/17005 and PRs listed inside to be merged

fix links pointing to old go.d repo

---

charts/netdata/templates/child/daemonset.yaml
charts/netdata/values.yaml

Since the child is running on network mode host, which by default also starts the web dashboard on port 19999 means running netdata on public worker nodes are exposed without authentication to the internet, especially when using different Kubernetes distributions which normally by default also not having any firewall on node ports configured.
As recommended by Netdata it's possible to bind the web port to a private IP or localhost, see https://learn.netdata.cloud/docs/netdata-agent/securing-netdata-agents/#expose-netdata-only-in-a-private-lan, the helm chart is not working at all because the readiness and liveness probes are using the public node IP by default (due to network mode host).
This partically fixes #402, at least allows to bind the web dashboard to 127.0.0.1 and bringing the …

Allow to override the liveness and readiness probe host #402

---

.github/workflows/checks.yml

Fixes (#462)
```
Run actions/setup-python@v5.3.0
Installed versions
Version 3.7 was not found in the local cache
Error: The version '3.7' with architecture 'x64' was not found for Ubuntu 24.04.
The list of all available versions can be found he
```

ci: bump setup-python version to 3.13

---

charts/netdata/sdconfig/k8s.yml
charts/netdata/templates/_helpers.tpl
charts/netdata/templates/child/configmap.yaml
charts/netdata/templates/child/daemonset.yaml
charts/netdata/values.yaml

[service-discovery sidecar](https://github.com/netdata/agent-service-discovery) is no longer needed as its functionality is built into go.d.plugin.
This change was announced in [v2.1.0 deprecation notice](https://github.com/netdata/netdata/releases/tag/v2.1.0#v210-deprecation-notice).

rm service discovery sidecar for Netdata v2.2+

---

charts/netdata/templates/child/daemonset.yaml
charts/netdata/templates/k8s-state/deployment.yaml
charts/netdata/templates/parent/deployment.yaml

Since we have dynamic rooms it makes sense for this parameter to be optional.

adding conditional to claim rooms

---

charts/netdata/templates/parent/deployment.yaml
charts/netdata/values.yaml

Resolves #449 . This ads the ability run the parent pod as a select uid/gid, and run an init container that will set file permissions appropriately on the mounted directories.

Add Startup Volume Permission Enforcement

---

charts/netdata/values.yaml

This PR fixes duplicate metrics collection from kubelet by aligning the static job names in our Helm chart with the dynamic job names used by the [locallisteners discoverer](https://github.com/netdata/netdata/blob/2db34d2af56468b009c1bf4de6989fc09298f93c/src/go/plugin/go.d/config/go.d/sd/net_listeners.conf#L345-L354).
We were collecting metrics from kubelet twice:
- Once through the static k8s_kubelet job defined in our Helm chart
- Once through the dynamic local job discovered by the locallisteners discoverer
Both jobs were running simultaneously because they had different names, resulting in duplicate metrics.

deduplicate kubelet/kubeproxy metrics collection
